package com.institutopacifico.actualidad.modules.pageviewer.themes

import android.graphics.Color
import android.support.v4.content.ContextCompat
import br.tiagohm.markdownview.css.InternalStyleSheet
import com.institutopacifico.actualidad.R
import com.institutopacifico.actualidad.application.ApplicationClass

/**
 * Created by mobile on 5/17/17.
 * Fernando Rubio Burga
 */

open class PrimalThemeCssModule : InternalStyleSheet() {
    init {
        this.addRule("*", *arrayOf("box-sizing: border-box"))
        this.addRule("h1", *arrayOf("font-size: 26px", "margin-top: 20px", "margin-bottom: 10px", "line-height: 25px"))
        this.addRule("h2", *arrayOf("font-size: 28px", "margin-top: 20px", "margin-bottom: 10px", "font-weight: 500", "line-height: 1.1"))
        this.addRule("h3", *arrayOf("font-size: 26px", "margin-top: 20px", "margin-bottom: 10px", "margin-top: 20px", "margin-bottom: 10px", "font-weight: 500", "line-height: 1.1"))
        var CategoryColor = Integer.toHexString(ContextCompat.getColor(ApplicationClass.context, R.color.colorPrimaryDark))
        if (CategoryColor.length > 6) {
            CategoryColor = CategoryColor.substring(CategoryColor.length - 6)
        }
        this.addRule("h4", *arrayOf("font-size: 20px", "margin-top: 10px", "margin-bottom: 10px", "font-weight: 500", "line-height: 1.1", "color:" + "#" + CategoryColor))
        this.addRule("h5", *arrayOf("font-size: 16px", "margin-top: 10px", "margin-bottom: 10px", "font-weight: 500", "line-height: 1.1"))
        this.addRule("h6", *arrayOf("font-size: 14px", "margin-top: 10px", "margin-bottom: 10px", "font-weight: 500", "line-height: 1.1"))
        this.addRule("hr", *arrayOf("margin-top: 20px", "margin-bottom: 20px", "border: 0", "border-top: 1px solid #eee"))
        this.addRule("p", *arrayOf("margin:0", "text-align:justify", "line-height: 23px", "font-size:16px"))
        this.addRule("p strong", *arrayOf("color:#949494", "font-size:16px"))
        this.addRule(".container", *arrayOf("margin:20px !important", "padding:0px"))
        this.addRule("strong", *arrayOf("font-weight:700"))
        this.addRule("em", *arrayOf("font-style: italic"))
        this.addRule("a", *arrayOf("color: #337ab7", "text-decoration: none", "word-wrap: break-word"))
        this.addRule("img", *arrayOf("vertical-align: middle", "border: 0", "width: 100%", "height: auto", "border:1px solid #C3C3C3", "margin-top:10px", "margin-bottom:20px", "display:block"))
        this.addRule("code", *arrayOf("padding: 2px 4px", "font-size: 90%", "color: #c7254e", "background-color: #f9f2f4", "white-space: nowrap", "border-radius: 4px", "font-family: Menlo,Monaco,Consolas,\"Courier New\",monospace"))
        this.addRule("pre code", *arrayOf("padding: 0", "white-wrap: pre-wrap", "white-space: pre", "background-color: transparent", "border-radius: 0"))
        this.addRule("pre", *arrayOf("display: block", "padding: 9.5px", "margin: 0 0 10px", "font-size: 13px", "line-height: 1.42857143", "color: #333", "background-color: #f5f5f5", "border: 1px solid #ccc", "border-radius: 4px", "font-family: Menlo,Monaco,Consolas,\"Courier New\",monospace", "overflow: auto"))
        this.addRule("blockquote", *arrayOf("padding: 0px 20px", "margin: 0 0 20px", "font-size: 14px", "border-left: 5px solid #eee"))
        this.addRule("ul", *arrayOf("margin-top: 0", "margin-bottom: 10px"))
        this.addRule("ol", *arrayOf("margin-top: 0", "margin-bottom: 10px"))
        this.addRule("ol ol", *arrayOf("margim-bottom: 0", "text-align:justify", "line-height: 23px", "font-size:16px"))
        this.addRule("ol ul", *arrayOf("margim-bottom: 0"))
        this.addRule("ul ol", *arrayOf("margim-bottom: 0"))
        this.addRule("ul ul", *arrayOf("margim-bottom: 0"))
        this.addRule("table", *arrayOf("border:1px #ccc solid", "padding:10px", "width:100%", "border-collapse: collapse", "margin-bottom:20px", "margin-top:10px"))
        this.addRule("tr, td", *arrayOf("border:2px #ccc solid", "padding:10px", "border-collapse: collapse", "font-family:Verdana", "font-size:13px"))
        this.addRule("th", *arrayOf("background-color: #81969F", "color: white"))
        this.addRule("tr:nth-child(even)", *arrayOf("background-color: #f2f2f2"))
        this.addRule("thead", *arrayOf("width:100% !important"))
        this.addRule(".table_container", *arrayOf("width:100%", "overflow:scroll"))
        //TODO: ADD MEdia Screen
        //  this.addRule("@media screen and (min-width: 10px)", *arrayOf("width:100%","overflow:scroll"))
        this.addRule("th[align=left]", *arrayOf("text-align: left"))
        this.addRule("th[align=center]", *arrayOf("text-align: center"))
        this.addRule("th[align=right]", *arrayOf("text-align: right"))
        this.addRule("td[align=left]", *arrayOf("text-align: left"))
        this.addRule("td[align=center]", *arrayOf("text-align: center"))
        this.addRule("td[align=right]", *arrayOf("text-align: right"))
        this.addRule("abbr", *arrayOf("border-bottom: 1px dotted #777"))
        this.addRule("mark", *arrayOf("padding: 0.2em", "background-color: #fcf8e3"))
        this.addRule("sub", *arrayOf("position: relative", "font-size: 75%", "line-height: 0", "vertical-align: baseline", "bottom: -0.25em"))
        this.addRule("sup", *arrayOf("position: relative", "font-size: 75%", "line-height: 0", "vertical-align: baseline", "top: -0.5em"))
        this.addRule("kbd", *arrayOf("padding: 2px 4px", "font-size: 90%", "color: #fff", "background-color: #333", "border-radius: 3px", "box-shadow: inset 0 -1px 0 rgba(0,0,0,0.25)", "font-family: Menlo, Monaco, Consolas, \"Courier New\", monospace"))
        this.addRule("math", *arrayOf("color: inherit"))
        this.addRule("lbl", *arrayOf("display: inline-block", "padding: 0 10px", "background: #1e87f0", "line-height: 1.5", "font-size: 12px", "color: #fff", "vertical-align: middle", "white-space: nowrap", "border-radius: 2px", "text-transform: uppercase;"))
        this.addRule("button", *arrayOf("margin: 0", "overflow: visible", "display: inline-block", "padding: 0 30px", "vertical-align: middle", "font-size: 14px", "line-height: 38px", "text-align: center", "color: #222", "border: 1px solid #e5e5e5", "background-color: transparent"))
        this.addRule(".lbl-success", *arrayOf("background-color: #32d296"))
        this.addRule(".lbl-warning", *arrayOf("background-color: #faa05a"))
        this.addRule(".lbl-danger", *arrayOf("background-color: #f0506e"))
        this.addRule(".container", *arrayOf("padding-right: 15px", "padding-left: 15px", "margin-right: auto", "margin-left: auto"))
        this.addRule(".task-list-item", *arrayOf("list-style-type: none"))
        this.addRule(".task-list-item-checkbox", *arrayOf("vertical-align: middle", "margin: 0em 0.2em 0.25em -1.6em"))
        this.addRule(".footnotes p", *arrayOf("margin: 0"))
        this.addRule(".footnotes li", *arrayOf("margin-top: 2px", "margin-bottom: 2px"))
        this.addRule(".player", *arrayOf("position: relative", "padding-bottom: 56.25%", "padding-top: 25px", "height: 0"))
        this.addRule(".player iframe", *arrayOf("position: absolute", "top: 0", "left: 0", "width: 100%", "height: 100%"))
        this.addRule(".twitter-follow-button", *arrayOf("vertical-align: middle"))
        this.addRule(".hljs", *arrayOf("display: block", "overflow-x: auto", "color: #4d4d4c", "padding: 0.5em"))
        this.addRule(".hljs-type", *arrayOf("color: #880000"))
        this.addRule(".hljs-params", *arrayOf("color: #880000"))
        this.addRule(".hljs-string", *arrayOf("color: #880000"))
        this.addRule(".hljs-number", *arrayOf("color: #880000"))
        this.addRule(".hljs-selector-id", *arrayOf("color: #880000"))
        this.addRule(".hljs-selector-class", *arrayOf("color: #880000"))
        this.addRule(".hljs-comment", *arrayOf("color: #8e908c"))
        this.addRule(".hljs-quote", *arrayOf("color: #8e908c"))
        this.addRule(".hljs-template-tag", *arrayOf("color: #880000"))
        this.addRule(".hljs-tag", *arrayOf("color: #880000"))
        this.addRule(".hljs-name", *arrayOf("color: #880000"))
        this.addRule(".hljs-deletion", *arrayOf("color: #880000"))
        this.addRule(".hljs-title", *arrayOf("color: #880000", "font-weight: bold"))
        this.addRule(".hljs-section", *arrayOf("color: #880000", "font-weight: bold"))
        this.addRule(".hljs-regexp", *arrayOf("color: #BC6060"))
        this.addRule(".hljs-symbol", *arrayOf("color: #BC6060"))
        this.addRule(".hljs-variable", *arrayOf("color: #BC6060"))
        this.addRule(".hljs-template-variable", *arrayOf("color: #BC6060"))
        this.addRule(".hljs-link", *arrayOf("color: #BC6060"))
        this.addRule(".hljs-attribute", *arrayOf("color: #eab700"))
        this.addRule(".hljs-selector-attr", *arrayOf("color: #BC6060"))
        this.addRule(".hljs-selector-pseudo", *arrayOf("color: #BC6060"))
        this.addRule(".hljs-literal", *arrayOf("color: #78A960"))
        this.addRule(".hljs-built_in", *arrayOf("color: #397300"))
        this.addRule(".hljs-builtin-name", *arrayOf("color: #397300"))
        this.addRule(".hljs-bullet", *arrayOf("color: #397300"))
        this.addRule(".hljs-code", *arrayOf("color: #397300"))
        this.addRule(".hljs-addition", *arrayOf("color: #397300"))
        this.addRule(".hljs-meta", *arrayOf("color: #1f7199"))
        this.addRule(".hljs-meta-string", *arrayOf("color: #4d99bf"))
        this.addRule(".hljs-keyword", *arrayOf("color: #000000"))
        this.addRule(".hljs-selector-tag", *arrayOf("color: #000000"))
        this.addRule(".hljs-emphasis", *arrayOf("font-style: italic"))
        this.addRule(".hljs-strong", *arrayOf("font-weight: bold"))
    }
}
